### ISSUE TITLE
Crash on Android 12

### ISSUE THREAD

**Issue by woodii** [airbnb/epoxy#1199]
According to Firebase Crashlytics users with Google Pixel Devices and Android 11 are experiencing crashes every time they start up our app.
I belive that that data is not correct and its actually Android 12 Beta as a few users stated that they can't start the app and I can't see any A12 non fatal errors logged aswell.

Unfortunately I can't reproduce the error on emulators or physical devices (including Pixel devices) running Android 11 or 12.

```
Fatal Exception: com.airbnb.epoxy.IllegalEpoxyUsage: You must set an id on a model before adding it. Use the @AutoModel annotation if you want an id to be automatically generated for you.
       at com.airbnb.epoxy.EpoxyController.addInternal(EpoxyController.java:502)
       at com.airbnb.epoxy.EpoxyModel.addTo(EpoxyModel.java:337)
```

The error is a bit missleading as I am setting an id via the builder pattern with `.id("***")` before calling `.addTo(this)`
But I have no idea what the real cause is.

epoxy Version: 4.6.1 (it's also happening on older versions e.g. 4.0.0-beta6)

**Comment by johnpaulmckean** [comment]
I've been seeing this as well.

**Comment by elihart** [comment]
Hm, we're not seeing this at all ourselves and I don't see how this code path could be affected by the OS version or how this would be possible if you are setting the id first. If you can give me more information that would help

**Comment by johnpaulmckean** [comment]
Details I have from Bugsnag:
```
OS Versions: 11 (but based on users who reach out, it is 12 beta)
Manufacturers: Google
Models: [Pixel 3 XL, Pixel 3a XL, Pixel 4a, Pixel 5]
```

**Comment by woodii** [comment]
Unfortunately there is nothing special about that epoxy usage.
The controller is placed inside a flexbox-layout in a fragment.
The crashing controller is one of many on the screen but probably the first one with models as the other ones rely on network-data.

More interestingly the crash occurred on one of our devices as well but not immediately after installing the app. It happend half a week later on appstart.

Just to emphasise the statistics above:
98% Android 11, and 2% Android 12 (imo its only 12 and just wrong reporting)
And distributed across various Pixel devices.

Just let me know if I can provide any specific information.

**Comment by anurag-goyal** [comment]
To add to woodii's point. We are also experiencing the same issue on my app and the common thread is the Flexbox layout. We are also using the controller to places some views dynamically based on the server response.

**Comment by thagikura** [comment]
Hi, I'm the owner of the flexbox-layout. @woodii or @anurag-goyal , do you happen to have an example project that can reproduce the issue?

**Comment by woodii** [comment]
Hi @thagikura thanks for getting in touch. Unfortunately I don't have a version or device where this issue is reproducable in a reliable way.
I am currently trying to get users of our app to test a version with reduced featureset to see if the issue is related to that one spot with the flexbox or a more general issue.
As soon as I have more info I'll let you know.

**Comment by slavkoder** [comment]
Hey @woodii friendly ping to see if you were able to reproduce the issue consistently.

**Comment by woodii** [comment]
@slavkoder Unfortunately not on several of our devices. Fortunately I am in touch with one of our users who can reproduce the issue. I am currently trying to narrow down the error. At least from what I know so far it should not be an general epoxy android 12 issue and more implementation specific. But I'll let you know as soon as I learn more.

**Comment by larryng** [comment]
I've been seeing this as well.  Our app uses flexbox-layout but not on the screen with this issue.  It seems to only be reproducible in release/obfuscated builds -- debug is unaffected.

**Comment by woodii** [comment]
I now have several user who stated that the issue does not happen directly after installing and instead several days after. Looks like some app otimization for installed apps in Android 12?! I tried my luck in the google issue tracker: https://issuetracker.google.com/issues/197818595

**Comment by AdamMc331** [comment]
Just to provide an additional data point - I'm seeing this happen in our application as well. Only on Pixel devices, for us it's 97% of the time on Android 12. 

I've installed on my Pixel 3 XL running Android 12, and haven't been able to reproduce _yet_, but I'll keep trying.

**Comment by woodii** [comment]
Got some good news from Googles bugtracker related to this issue:
> I reproed and found the offending ART optimization that triggers this. The optimization is only in Android 12. Investigating now on a fix.

**Comment by elihart** [comment]
Good news! Thanks for following up

**Comment by AdamMc331** [comment]
That is great! Beta 05 just hit today, as well: https://android-developers.googleblog.com/2021/08/android12beta5.html

It's suggesting we're weeks away from a stable release. Should this be cause for concern? Even if it's on the Android side and not Epoxy's fault, I don't want the app to break simply because people are eager to try the new OS. 😰

**Comment by rossbacher** [comment]
We can also repro this now in our codebase (when using R8) do you have optimization enabled? Or just regular r8?

**Comment by woodii** [comment]
> Hey folks, we finally got to the bottom of the issue, and are working to make the fix available to Android 12 ASAP. However, we cannot guarantee that all Android 12 devices will not have the issue.
> 
> For your information the issue is due to a new optimization in ART in Android 12 called partial load store elimination, which tries to eliminate or move an object allocation when that object is only used locally in a method.
> 
> So for a workaround on the given crash in #1, what you can do is at the point of allocating the EpoxyModel which will be passed to "EpoxyController.addInternal", store that object in a local field. This will make sure the optimization doesn't try to remove the allocation.

Here are some more recent news from google. Apparently they have a fix and are working on rolling it out. I haven't tried the suggested workaround but I am quite certain that I would have to add that to every single epoxy model in our app - which are a lot. Would it be possible that you implement such a workaround in your lib?

@rossbacher we have the following options enabled: minifyEnabled, shrinkResources. So as far as I know optimization is enabled by default?

**Comment by blah1234** [comment]
I've submitted a pull request https://github.com/airbnb/epoxy/pull/1234, where I've made a change to
epoxy-processor/src/main/java/com/airbnb/epoxy/processor/KotlinModelBuilderExtensionWriter.kt

so that in generated kotlin extension functions, the created epoxy model is assigned to a local field first before passing the object to ModelCollector.add()

I think this implementation is the temporary workaround suggested by the google engineer (https://issuetracker.google.com/issues/197818595#comment20) before the bug fix for the root cause is rolled out in future releases of Android 12

**Comment by elihart** [comment]
Yes, that was the suggested change, but @rossbacher looked at the byte code and doesn't believe it will help. we can try it though

**Comment by rossbacher** [comment]
I don't think this will work, I did some more investigations and found that outlining during R8 optimization seems to be responsible for this issue to show up (well it is triggering the bug in ART)

e.g. if you have Kotlin code like this:

```Kotlin
generatedExtensionFunction {
    id("some_id")
}
```

that you will have if you use the generated extension functions, it will be compiled (because the extension function is marked as to inlined) to something like this:

```Kotlin
ExtensionFunctionDefinedModel_ epoxyControllerModel_ = new ExtensionFunctionDefinedModel_();
epoxyControllerModel_.id("some_id");
add(epoxyControllerModel_);
```

This works, even with the bug in ART. However if we run R8 with optimization enabled this will be transformed into:

```Kotlin
EpoxyModel<?> r1 = outline.m135855("some_id");
add(r1);
```

This is done because the outlining optimization detected that what we did here was done over and over again in the code and it outlined it (See more info at https://jakewharton.com/r8-optimization-method-outlining/)

The actual outlined code looks like this:

```Kotlin
public static ExtensionFunctionDefinedModel_ m135855(String str) {
    ExtensionFunctionDefinedModel_ epoxyControllerModel_ = new ExtensionFunctionDefinedModel_();
    epoxyControllerModel_.id(str);
    return epoxyControllerModel_;
}
```

This seems to trigger the ART bug that optimized the content of the `m135855` function away, well at least the call to the `id` function.

Sadly there is no option in R8 to just disabling outlining(you can disable optimization and not see this issue anymore, but that has some app size impact), so I forked R8 and added a flag for that and the `.dex` code that comes out of that looks good, we still need to test this I'll keep you posted about the results.

I know that forking R8 does sound scary and might not be a good option for everyone but I don't see any other way to work around this issue.

**Comment by rossbacher** [comment]
So yeah the fix with disabling outlining works on our side. I know that forking R8 is not the best thing to do for everyone. I can give a bit more details and show the modification I made if anyone is interested.

**Comment by woodii** [comment]
Hey @rossbacher,

thanks for further investigating this issue.

As it might take some time until google's fix is rolled out compeletely and this issue still prevents users with A12 to use our app reliably I am considering realeasing a fix with the modified R8 version.

It would be really helpful if you could share your R8 version and some comments on what you have changed/how to use it.
Many thanks in advance!

**Comment by woodii** [comment]
Now I am even more hyped and want to distribute a new version to get rid of the ~ 90 app crashes/day caused by this. Could you just send me your r8 version and how to use it?

**Comment by rossbacher** [comment]
@woodii you really don't want to use some unauthorized R8 version, I could inject anything into your code. I had sadly no luck with providing a patch to Google as they block contribution on the R8 repo and I had not luck reaching out to get myself allowed to contribute. But let me explain of what I did and you can do the same and build your own R8 fork. 

This is for 2.2.66 version of R8, which is the one that AGP 4.2.1 is depends on, but the same can be done to any R8 version.

The only thing you need to do is go here: https://r8.googlesource.com/r8/+/refs/tags/2.2.66/src/main/java/com/android/tools/r8/utils/InternalOptions.java#164
and insert after that line:

```java
outline.enabled = System.getProperty("com.android.tools.r8.disableoutlining") == null;
```

You might also want to update the version here: https://r8.googlesource.com/r8/+/refs/tags/2.2.66/src/main/java/com/android/tools/r8/Version.java

Then run `tools/build_r8lib.py -e` which will build the lib. You can publish it to local maven using the pom file of the original (with updated version)  https://mvnrepository.com/artifact/com.android.tools/r8?repo=google

If on a mac I'd do all of that inside a disk image which is case sensitive (that is what i did) just to be sure that case is not an issue here.

To use the version that you just created just add a dependency to `com.android.tools:r8:<version>` to your `build.gradle` file **before** you define your dependency to AGP. If you have a buildSrc folder, do the same thing in the `build.gradle` file in there.

Now you can disable outlining by just adding `systemProp.com.android.tools.r8.disableoutlining=true` to your `gradle.properties` file.

**Comment by woodii** [comment]
Thanks for your advice and especially making it that clear ... yeah r8 does codemodification and could potentially do some evil stuff to your app too.
I am just a bit desperate already as this issue blocks a huge amount of users to use our apps reliably.
Thank you so much for your detailed explanation.

**Comment by a10033135** [comment]
Android 12 was released yesterday,
Has anyone tested the same issue Or confirm that this issue has been fixed?
Many thanks in advance!

**Comment by woodii** [comment]
@a10033135 A colleague experienced the crash after updating to stable today. Either the app has to be reinstalled as the optimization was already done (not sure how this actually works). Or the fix is simply not in this version (which is very likely)

I rolled out a new version of my app with @rossbacher fix today and will keep you posted if it helped. Only thing that did not work as described was `tools/build_r8lib.py -e` -> always threw some errors even if I tried to adapt the script and I ended up just using `tools/gradle.py d8 r8` to build the jar.

**Comment by voneskuba** [comment]
> Android 12 was released today, Has anyone tested the same issue Or confirm that this issue has been fixed? Many thanks in advance!

We have same issue with epoxy version 4.6.3 and stable AN12 @a10033135

**Comment by TomoyaShibata** [comment]
Fixed to ART bugs seems to have been included in Nobember monthly update for Pixel. https://issuetracker.google.com/issues/197818595#comment33
> Hi all, the fix discussed in comment #22 is in the tree and current builds of the ART Module. The fix will be part of the the November monthly update for Pixel. Hopefully the fix will be with you shortly.

Now, An update is available.
https://support.google.com/pixelphone/thread/133452459/google-android-pixel-security-update-nov-2021?hl=en

Can you confirm that this issue has been fixed?

**Comment by KirkBushman** [comment]
What about Pixel 3 and 3XL, which are no longer supported? Will they receive the fix in a later patch?

**Comment by ubuntudroid** [comment]
@KirkBushman better ask in the Google issue tracker thread. Googlers should be able to answer that question.

**Comment by haohaozaici** [comment]
I set `-dontoptimize` in `proguard-rules.pro`, but this problem still occurs.

**Comment by woodii** [comment]
@haohaozaici unfortunately there is still no fix you can do to solve this issue by yourself. The only option you have is to inform the user to install the latest Android patches.

**Comment by haohaozaici** [comment]
This problem mainly occurs in Huawei and Magic Android 12 devices. It is normal when r8 optimization is not turned off.

You can check whether the configuration file contains the `-dontoptimize` option, which will turn off r8 optimization and need to be deleted.

```
.../app/build/outputs/mapping/release/configuration.txt
-dontoptimize
```

This command will actively trigger the system ART optimization, and then restart the application to verify the problem.
``` shell
adb shell cmd package compile -m speed -f packageName
```
