### ISSUE TITLE
IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by vkislicins** [airbnb/epoxy#770]
I’m using Epoxy in my project with the following setup:

Controller:

 ```
<…>
override fun buildModels(data: Data?) {
        val carouselItemModels = mutableListOf<CarouselItemViewModel_>()
        data?.carouselItemModels?.forEach {
            carouselItemModels.add(CarouselItemViewModel_()
                    .id(CATEGORY_ID_CAROUSEL_ITEM, it.position)
                    .item(it)
            )
        }

        val isCarouselVisible = carouselModels.isNotEmpty()

        val header = SimpleTextHeaderEpoxyViewModel_()
                .id(CATEGORY_ID_HEADER)
                .title(context?.getString(R.string.carousel_header))
                .background(R.color.lightGrey2)
                .visibility(isCarouselVisible)

        val carousel = SnappingCarouselModel_()
                .id(CATEGORY_ID_CAROUSEL)
                .models(carouselItemModels)
                .numViewsToShowOnScreen(2.12f)
                .padding(Carousel.Padding.dp(8, 0))
                .background(R.color.lightGrey2)
                .visibility(isCarouselVisible)

        EpoxyModelGroup(
                R.layout.epoxy_carousel_with_header,
                listOf(
                        header as EpoxyModel<SimpleTextHeaderEpoxyView>,
                        carousel as EpoxyModel<SnappingCarousel>
                )
        ).addTo(this)

        data?.matches?.forEach {
            MatchViewModel_()
                    .id(it.id)
                    .item(it)
                    .addTo(this)
        }
    }
```

`setData()` is triggered from the Rx chain:

```
 fun bindFeedData() {
        addDisposable(
                userRepository.getUser().toFlowable()
                        .flatMap {
                            Flowable.combineLatest(
                                    matchesRepository.getMatches(it.id),
                                    carouselDataRepository.getAllCarouselData(it.id),
                                    BiFunction { matches: List<Match>, carouselModels: MutableList<CarouselModel> ->
                                        Data(matches, carouselModels, it)
                                    }
                            )
                        }
                        .sample(500, TimeUnit.MILLISECONDS, true)
                        .subscribeOn(schedulerProvider.io())
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe({ view.showData(it) }, { error -> processError(error) })) //showData calls setData
    }
```

Both `getMatches` and `getAllCarouselData` bind to the local database tables and return Flowables. There’s other code that syncs data with the server and updates both tables, where the data can be added, removed or the table will be completely cleared. This ends up with the following UI interactions:

1) Carousel item might be added, or removed from the carousel
2) Carousel and the header might be collapsed (no longer visible) or expanded (an item is added)
3) A match item can be added to the main feed, or removed from it.

Since releasing this feature, I’ve been seeing steady amount of crashes in the field. They happen rarely and represent a small percentage of users, but I’m still curious to investigate. Here’s the stacktrace:

```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner + 3430(ViewGroup.java:3430)
       at android.view.ViewGroup.addView + 3301(ViewGroup.java:3301)
       at android.view.ViewGroup.addView + 3246(ViewGroup.java:3246)
       at androidx.recyclerview.widget.RecyclerView$5.addView + 848(RecyclerView.java:848)
       at androidx.recyclerview.widget.ChildHelper.addView + 107(ChildHelper.java:107)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.canScrollHorizontally(RecyclerView.java:39)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt + 8424(RecyclerView.java:8424)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.canScrollVertically(RecyclerView.java:16)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView + 8382(RecyclerView.java:8382)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.canScrollVertically(RecyclerView.java:15)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView + 8370(RecyclerView.java:8370)
       at androidx.recyclerview.widget.LinearLayoutManager.onAnchorReady(LinearLayoutManager.java:119)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk + 1571(LinearLayoutManager.java:1571)
       at androidx.recyclerview.widget.LinearLayoutManager.onAnchorReady(LinearLayoutManager.java:101)
       at androidx.recyclerview.widget.LinearLayoutManager.fill + 1517(LinearLayoutManager.java:1517)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollBy + 1331(LinearLayoutManager.java:1331)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy + 1075(LinearLayoutManager.java:1075)
       at androidx.recyclerview.widget.RecyclerView.scrollStep + 1829(RecyclerView.java:1829)
       at androidx.recyclerview.widget.RecyclerView.scrollByInternal + 1928(RecyclerView.java:1928)
       at androidx.recyclerview.widget.RecyclerView.onTouchEvent + 3253(RecyclerView.java:3253)
       at android.view.View.dispatchTouchEvent + 7269(View.java:7269)
       at android.view.ViewGroup.dispatchTransformedTouchEvent + 2235(ViewGroup.java:2235)
       at android.view.ViewGroup.dispatchTouchEvent + 1932(ViewGroup.java:1932)
       at android.view.ViewGroup.dispatchTransformedTouchEvent + 2241(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent + 1946(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent + 2241(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent + 1946(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent + 2241(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent + 1946(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent + 2241(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent + 1946(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent + 2241(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent + 1946(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent + 2241(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent + 1946(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent + 2241(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent + 1946(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent + 2241(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent + 1946(ViewGroup.java:1946)
       at android.view.ViewGroup.dispatchTransformedTouchEvent + 2241(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent + 1946(ViewGroup.java:1946)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent + 1977(PhoneWindow.java:1977)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent + 1427(PhoneWindow.java:1427)
       at android.app.Activity.dispatchTouchEvent + 2428(Activity.java:2428)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent + 69(WindowCallbackWrapper.java:69)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent + 69(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent + 1925(PhoneWindow.java:1925)
       at android.view.View.dispatchPointerEvent + 7449(View.java:7449)
       at android.view.ViewRootImpl.deliverPointerEvent + 3623(ViewRootImpl.java:3623)
       at android.view.ViewRootImpl.deliverInputEvent + 3551(ViewRootImpl.java:3551)
       at android.view.ViewRootImpl.doProcessInputEvents + 4863(ViewRootImpl.java:4863)
       at android.view.ViewRootImpl.enqueueInputEvent + 4823(ViewRootImpl.java:4823)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent + 4975(ViewRootImpl.java:4975)
       at android.view.InputEventReceiver.dispatchInputEvent + 179(InputEventReceiver.java:179)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents + 171(InputEventReceiver.java:171)
       at android.view.ViewRootImpl.doConsumeBatchedInput + 4943(ViewRootImpl.java:4943)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run + 4997(ViewRootImpl.java:4997)
       at android.view.Choreographer$CallbackRecord.run + 776(Choreographer.java:776)
       at android.view.Choreographer.doCallbacks + 579(Choreographer.java:579)
       at android.view.Choreographer.doFrame + 546(Choreographer.java:546)
       at android.view.Choreographer$FrameDisplayEventReceiver.run + 762(Choreographer.java:762)
       at android.os.Handler.handleCallback + 800(Handler.java:800)
       at android.os.Handler.dispatchMessage + 100(Handler.java:100)
       at android.os.Looper.loop + 194(Looper.java:194)
       at android.app.ActivityThread.main + 5371(ActivityThread.java:5371)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke + 525(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 833(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main + 600(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

I wasn’t able to reproduce this manually, but if I manipulate and loop my observables to add and delete data with minimal interval in between, I was able to crash the app a few times.

My question is - am I doing something obviously wrong in my controller? Should I be staging the updates? Maybe I should do the carousel first, before updating the rest of the feed? Any thoughts are much appreciated!

**Comment by elihart** [comment]
Thanks for the detailed bug report. I don't see any issues with your code, and nothing you could do in your models should be able to cause an issue like this I think.

It could potentially be a bug within RecyclerView. Which version are you using?

I haven't seen an issue like this in our app before, but we also don't invalidate that frequently.

I would suggest changing your EpoxyController to build and diff models in the background. That will give you better UI performance since you are doing it so frequently, and _maybe_ might help with this issue.

**Comment by vkislicins** [comment]
Thanks for your reply!
In terms of the RecyclerView, I’m using androidx 1.1.0-alpha01. Will try to update to alpha06 and see if that makes any difference. Will also move the default EpoxyController build and diff to the background in case it helps.

**Comment by vkislicins** [comment]
Released a new version of the app with the suggested changes - unfortunately still seeing quite a lot of crashes with that exception. I guess will try to raise a bug with RecyclerView

**Comment by tinsukE** [comment]
@vkislicins did you create a issue for RecyclerView? Any link to it?

**Comment by vkislicins** [comment]
@tinsukE I have, but the bug is not public. I'll post on this thread once there's an update.

Are you seeing a similar issue?

**Comment by tinsukE** [comment]
@vkislicins I'm not using Epoxy, but managed to reproduce a very similar issue (same crash, but slightly different origin in the stack trace) consistently in our App. For us it was related to have a shared element transition and a RecyclerView.ItemAnimator running animations at the same time.
I managed to work it around by not running the shared element transition when the item animator had running animations.
Our crash would also fixed by updating the RecyclerView library to its 1.1.0-beta03 version, so I'll remove the workaround when 1.1.0 goes stable.

**Comment by vkislicins** [comment]
@tinsukE interesting. I'm still seeing the crash with 1.1.0-beta03

**Comment by mochadwi** [comment]
@vkislicins & @tinsukE is this related to your issue?

https://stackoverflow.com/a/59355664/3763032

**Comment by dcarr622** [comment]
Bumping this old issue because we're seeing a very large number of these crashes in production as our top crash.

Relevant facts:

- Epoxy version 4.6.2
- LinearLayoutManager is being used
- Happens across different lists in the app with different Epoxy models
- Our EpoxyController defaults are configured as follows per recommendations in this thread

```
EpoxyController.setGlobalDuplicateFilteringDefault(true)
EpoxyController.defaultDiffingHandler = EpoxyAsyncUtil.getAsyncBackgroundHandler()
EpoxyController.defaultModelBuildingHandler = EpoxyAsyncUtil.getAsyncBackgroundHandler()
```

This seems to happen in our app whenever the user performs an action that destroys and creates a new Activity, which made me think that it could have to do with Epoxy updating the RecyclerView at an inopportune time in the view's lifecycle but I haven't come up with a firm repro to support that theory. 

We aren't using TransitionManager on any of the impacted RecyclerViews. One of them happens to be in a MotionLayout but the crash occurs elsewhere as well.
